springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.nism.fg

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.alibaba.druid: debug
